version: 3.7

services:
  nest:
    image: node:15
    volumes:
      - ./:/app
    ports:
      - 4000:4000
    working_dir: /app
    environment:
    command: sh -c "yarn run start:dev"
  mongodb:
    image: mongo:4.4.3
    volumes:
      - skripsi-db:/data/db
    command: mongod --quiet --logpath /dev/null
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
      MONGO_INITDB_DATABASE: skripsi-db

volumes:
  skripsi-db:
